# Generated by Django 2.1.2 on 2018-10-30 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'City'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Country'},
        ),
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name_plural': 'Place'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name_plural': 'Type'},
        ),
        migrations.AddField(
            model_name='place',
            name='slug',
            field=models.SlugField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
