# Generated by Django 2.1.2 on 2018-10-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20181031_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventtimes',
            name='is_all_day',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
