# Generated by Django 2.0.8 on 2018-10-22 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesDirectors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'MoviesDirectors',
            },
        ),
        migrations.CreateModel(
            name='MoviesGenres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'MoviesGenres',
            },
        ),
        migrations.CreateModel(
            name='MoviesMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=100)),
                ('release_date', models.CharField(max_length=100)),
                ('cover_image', models.CharField(max_length=100)),
                ('review', models.CharField(max_length=100)),
                ('ASIN', models.CharField(max_length=100)),
                ('directors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.MoviesDirectors')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.MoviesGenres')),
            ],
        ),
        migrations.CreateModel(
            name='MoviesStudios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'MoviesStudios',
            },
        ),
        migrations.AddField(
            model_name='moviesmaster',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.MoviesStudios'),
        ),
    ]
