# Generated by Django 2.0.8 on 2018-10-22 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MoviesMaster',
            new_name='MoviesMasters',
        ),
    ]
