# Generated by Django 2.0.8 on 2018-10-22 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20181022_0803'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MoviesMasters',
            new_name='MoviesMaster',
        ),
    ]
