# Generated by Django 2.0.8 on 2018-10-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_moviesmaster_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesmaster',
            name='release_date',
            field=models.DateField(),
        ),
    ]
