# Generated by Django 2.0.8 on 2018-10-22 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20181022_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesmaster',
            name='ASIN',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='moviesmaster',
            name='cover_image',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='moviesmaster',
            name='prefix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='moviesmaster',
            name='sub_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
