# Generated by Django 2.0.8 on 2018-10-22 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20181022_0826'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviesdirectors',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='moviesgenres',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='moviesstudios',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='moviesdirectors',
            name='username',
        ),
        migrations.AddField(
            model_name='moviesdirectors',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='moviesdirectors',
            name='gender',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='moviesdirectors',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='moviesdirectors',
            name='middel_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='moviesdirectors',
            name='ph_number',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='moviesdirectors',
            name='website',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='moviesstudios',
            name='prefix',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='moviesstudios',
            name='website',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
