# Generated by Django 2.0.8 on 2018-10-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_auto_20181022_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesdirectors',
            name='gender',
            field=models.SmallIntegerField(choices=[('1', 'Male'), ('2', 'Female')], null=True),
        ),
    ]
