# Generated by Django 2.0.8 on 2018-10-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_auto_20181022_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesdirectors',
            name='ph_number',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
