# Generated by Django 2.0.8 on 2018-10-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_auto_20181022_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesdirectors',
            name='middel_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
