# Generated by Django 2.0.8 on 2018-10-24 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_auto_20181022_1255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesmaster',
            name='directors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.MoviesDirectors'),
        ),
        migrations.AlterField(
            model_name='moviesmaster',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.MoviesGenres'),
        ),
        migrations.AlterField(
            model_name='moviesmaster',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='movies.MoviesStudios'),
        ),
    ]
