# Generated by Django 2.1.2 on 2018-10-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_auto_20181024_0652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviesmaster',
            name='directors',
        ),
        migrations.AddField(
            model_name='moviesmaster',
            name='directors',
            field=models.ManyToManyField(to='movies.MoviesDirectors'),
        ),
    ]
